#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const configOutputPath = path.join(rootDir, 'config.js');

function parseEnv(filePath) {
    const values = {};
    if (!filePath || !fs.existsSync(filePath)) return values;

    const content = fs.readFileSync(filePath, 'utf8');

    for (const rawLine of content.split(/\r?\n/)) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;

        const equalsIndex = line.indexOf('=');
        if (equalsIndex === -1) continue;

        const key = line.slice(0, equalsIndex).trim();
        const value = line.slice(equalsIndex + 1).trim().replace(/^['"]|['"]$/g, '');
        values[key] = value;
    }

    return values;
}

const env = {
    ...parseEnv(envPath),
    ...process.env,
};

const SUPABASE_URL = env.SUPABASE_URL;
const SUPABASE_ANON_KEY = env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('Missing Supabase environment variables. Set SUPABASE_URL and SUPABASE_ANON_KEY in your shell or Netlify site settings.');
    process.exit(1);
}

const generatedConfig = `// Generated from environment variables. Do not edit this file manually.
window.__ENV__ = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};

const SUPABASE_URL = window.__ENV__.SUPABASE_URL;
const SUPABASE_ANON_KEY = window.__ENV__.SUPABASE_ANON_KEY;
`;

fs.writeFileSync(configOutputPath, generatedConfig);
console.log(`Generated ${path.relative(rootDir, configOutputPath)} using Netlify/ENV values.`);
